baseURL = "https://donna-og.github.io/"
languageCode = "en"
title = "Donna"

theme = "github.com/nunocoracao/blowfish/v2"

enableRobotsTXT = true
[pagination]
  pagerSize = 10
summaryLength = 30

[taxonomies]
  tag = "tags"
  category = "categories"
  author = "authors"

[outputs]
  home = ["HTML", "RSS", "JSON"]
